// Code generated by Wire. DO NOT EDIT.
//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject
package di

// Injectors from wire.go:

func BuildInjector() (*Event, error) {
	message := NewMessage()
	greeter := Greeter{
		Message: message,
	}
	event := &Event{
		Greeter: greeter,
	}
	return event, nil
}
